baseURL = 'https://principlesofdataengineering.org/'
locale = 'en-us'
title = 'Principles of Data Engineering'

[params]
  BookSection = 'docs'
  BookFavicon = 'favicon.svg'
  Description = 'A practical manual on building data representations of business entities in the real world.'
